Download dependencies from json file
gotenxds/NpmPackageDownloader pull request #7
Opened 2017-05-31 18:36 UTC by shayAlaluf

added option to download dependencies from json file (package.json)

2017-05-31 22:39 UTC, gotenxds requested changes
Fix this please.

2017-05-31 22:39 UTC, gotenxds commented on bin/npmDownload.js
> +    winston.error("No npmPackage of path to jsonFile were given!");
Typo ? should be "No npmPackage or path to jsonFile were given!"

2017-05-31 22:39 UTC, gotenxds commented on bin/npmDownload.js
> +if (!program.packages && !program.packagesFromJsonFile) {
Shouldn't this be an OR ?

2017-05-31 22:39 UTC, gotenxds commented on bin/npmDownload.js
> +let npmPackages = program.packagesFromJsonFile ? program.packagesFromJsonFile : program.packages;
What if both arguments where given ? merge into one list.

2017-05-31 22:39 UTC, gotenxds commented on coercions/packagesFromJsonFileCoercion.js
> +    const fileContent = JSON.parse(fs.readFileSync(jsonFilePath, "utf8"));
I don't love the fact you are using sync here but I guess It's fine for now.

2017-05-31 22:39 UTC, gotenxds commented on coercions/packagesFromJsonFileCoercion.js
> +    const devDependencies = attachNameAndVersion(fileContent.devDependencies);
You should check if the download dev-dependencies flag is true, its false by default.

2017-05-31 22:39 UTC, gotenxds commented on coercions/packagesFromJsonFileCoercion.js
> +    return orderedDependencies;
`return orderedDependencies.trimRight()`
This should make no difference, better safe then sorry.

2017-05-31 23:09 UTC, gotenxds commented on coercions/packagesFromJsonFileCoercion.js
> +module.exports = function (jsonFilePath) {
arrow function.

2017-06-01 11:10 UTC, shayAlaluf commented on coercions/packagesFromJsonFileCoercion.js
> +    const devDependencies = attachNameAndVersion(fileContent.devDependencies);
dev-dependencies flag will dowload all the dev dependencies of each dependency from the json file if set to true.
would u rather to set another flag to dowload dev dependencies from the json file?

2017-06-01 11:13 UTC, shayAlaluf commented on bin/npmDownload.js
> +if (!program.packages && !program.packagesFromJsonFile) {
no. if nither of them appear in the command, then it's an error.
you can call: -j "[path-to-json-file]" or: -p ...

2017-06-05 11:59 UTC, merged